min_version = "2026.9.17"

[settings]
task.run_auto_install = false

[tools]
# tools to check
act3 = "2.0.0"
bmm = "0.3.1"
envee = "0.1.0-alpha.2"
grafq = "0.2.0"
hours = "0.6.0"
kplay = "3.1.0"
mrj = "0.5.0"
mult = "0.3.1"
omm = "0.7.0"
punchout = "1.5.0"
tflens = "0.1.0-alpha.8"
ting = "0.1.1"
unreleased = "0.1.1"

# repo tools
actionlint = "latest"
yamlfmt = "latest"

[tool_alias]
act3 = "github:dhth/act3"
bmm = "github:dhth/bmm"
envee = "github:dhth/envee"
grafq = "github:dhth/grafq"
hours = "github:dhth/hours"
kplay = "github:dhth/kplay"
mrj = "github:dhth/mrj"
mult = "github:dhth/mult"
omm = "github:dhth/omm"
punchout = "github:dhth/punchout"
tflens = "github:dhth/tflens"
ting = "github:dhth/ting"
unreleased = "github:dhth/unreleased"

[tasks."lint:actions"]
description = "Lint GitHub Actions workflows"
run = "actionlint"

[tasks."lint:yaml"]
description = "Lint YAML files"
run = '''
yamlfmt \
    -lint \
    -quiet \
    -formatter 'retain_line_breaks_single=true' \
    $(git ls-files '*.yml' '*.yaml')
'''
