name: main

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      shell: ${{ steps.filter.outputs.shell }}
      workflows: ${{ steps.filter.outputs.workflows }}
      yml: ${{ steps.filter.outputs.yml }}
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            shell:
              - "mise-tasks/**"
              - "mise.toml"
              - "mise.lock"
            workflows:
              - ".github/**/*.yml"
              - "mise.toml"
              - "mise.lock"
            yml:
              - "**.yml"
              - "**.yaml"
              - "mise.toml"
              - "mise.lock"

  lint-shell:
    needs: changes
    if: ${{ needs.changes.outputs.shell == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up mise
        uses: jdx/mise-action@v5
        with:
          install_args: shellcheck
      - name: Lint shell scripts
        run: mise run lint:shell

  lint-workflows:
    needs: changes
    if: ${{ needs.changes.outputs.workflows == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up mise
        uses: jdx/mise-action@v5
        with:
          install_args: actionlint
      - name: Lint workflows
        run: mise run lint:actions

  lint-yaml:
    needs: changes
    if: ${{ needs.changes.outputs.yml == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up mise
        uses: jdx/mise-action@v5
        with:
          install_args: yamlfmt
      - name: Lint YAML
        run: mise run lint:yaml
